### ISSUE TITLE
 age_demo 

### ISSUE THREAD

**Issue by sybilW** [gaobb/DLDL#1]
when I run age_demo, i have some questions:
1.警告: 名称不存在或不是目录: ./External/matconvnet-1.0-beta18/matlab/mex 
2.i comments line 10 and line 11:
%opts.gpus = 12;
%gpuDevice(opts.gpus)
尝试将 SCRIPT vl_nnconv 作为函数执行:
/home/ws/downcode/label distribution learning/DLDL/External/matconvnet-1.0-beta18/matlab/vl_nnconv.m

出错 dldl_simplenn (line 288)
      res(i+1).x = vl_nnconv(res(i).x, l.weights{1}, l.weights{2}, ...

出错 age_demo (line 27)
res = dldl_simplenn(net, gpuArray(data), [], [], ...
am I wrong? and how can I fix these questions?

**Comment by gaobb** [comment]
Thank you very much for your interesting!
You need to compile matconvnet before running age demo. The details can be found [here](http://www.vlfeat.org/matconvnet/install/).

Good luck!
