### ISSUE TITLE
请问利用label和高斯分布生成一个 label distribution的方法都在哪里？matlab深度学习代码太不熟悉了

### ISSUE THREAD

**Issue by Sean-asc** [gaobb/DLDL#2]

**Comment by gaobb** [comment]
谢谢关注我们的工作。
年龄估计：https://github.com/gaobb/DLDL/blob/0f531971dc81d95c3f5e675051ef8d10caa44308/Age-Pose/dldl_age.m#L142-L147
头部姿态：https://github.com/gaobb/DLDL/blob/0f531971dc81d95c3f5e675051ef8d10caa44308/Age-Pose/dldl_pose.m#L159-L187
多标签：https://github.com/gaobb/DLDL/blob/0f531971dc81d95c3f5e675051ef8d10caa44308/utils/IFDLDLNet.m#L187-L192
语义分割：             https://github.com/gaobb/DLDL/blob/0f531971dc81d95c3f5e675051ef8d10caa44308/Segmentation/dldl_getBatch.m#L54-L81

**Comment by Sean-asc** [comment]
谢谢回复！但是现在我们有了新的处理方案，十分感谢！
&nbsp;


离殇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Bin-Bin ***@***.***&gt;; 
发送时间: 2023年2月22日(星期三) 中午12:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gaobb/DLDL] 请问利用label和高斯分布生成一个 label distribution的方法都在哪里？matlab深度学习代码太不熟悉了 (Issue #2)





 
谢谢关注我们的工作。
 年龄估计：https://github.com/gaobb/DLDL/blob/0f531971dc81d95c3f5e675051ef8d10caa44308/Age-Pose/dldl_age.m#L142-L147
 头部姿态：https://github.com/gaobb/DLDL/blob/0f531971dc81d95c3f5e675051ef8d10caa44308/Age-Pose/dldl_pose.m#L159-L187
 多标签：https://github.com/gaobb/DLDL/blob/0f531971dc81d95c3f5e675051ef8d10caa44308/utils/IFDLDLNet.m#L187-L192
 语义分割：             https://github.com/gaobb/DLDL/blob/0f531971dc81d95c3f5e675051ef8d10caa44308/Segmentation/dldl_getBatch.m#L54-L81
